"""add meeting participants

Revision ID: 2ee68132b23c
Revises: a21e9eaea9ab
Create Date: 2026-08-20 11:15:25.390885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ee68132b23c'
down_revision: Union[str, Sequence[str], None] = 'a21e9eaea9ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('participants', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'participants')
    # ### end Alembic commands ###
