"""add dialogue turns

Revision ID: 6dbcd456acb5
Revises: 2ee68132b23c
Create Date: 2026-08-20 15:01:59.323673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dbcd456acb5'
down_revision: Union[str, Sequence[str], None] = '2ee68132b23c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialogue_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('turn_order', sa.Integer(), nullable=False),
    sa.Column('speaker_label', sa.String(length=40), nullable=False),
    sa.Column('speaker_name', sa.String(length=150), nullable=False),
    sa.Column('speaker_user_id', sa.Integer(), nullable=True),
    sa.Column('name_confirmed', sa.Boolean(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_en', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['speaker_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialogue_turns_meeting_id'), 'dialogue_turns', ['meeting_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dialogue_turns_meeting_id'), table_name='dialogue_turns')
    op.drop_table('dialogue_turns')
    # ### end Alembic commands ###
