"""add uploaded_by to meetings

Revision ID: d5847b549b25
Revises: xxxx_unicode_fix
Create Date: 2026-09-08 08:04:45.909882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5847b549b25'
down_revision: Union[str, Sequence[str], None] = 'xxxx_unicode_fix'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dialogue_turns', 'speaker_label',
               existing_type=sa.NVARCHAR(length=40, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('dialogue_turns', 'speaker_name',
               existing_type=sa.NVARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('dialogue_turns', 'text',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.add_column('meetings', sa.Column('uploaded_by', sa.Integer(), nullable=True))
    op.alter_column('meetings', 'title',
               existing_type=sa.NVARCHAR(length=300, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.create_foreign_key(None, 'meetings', 'users', ['uploaded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.alter_column('meetings', 'title',
               existing_type=sa.NVARCHAR(length=300, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.drop_column('meetings', 'uploaded_by')
    op.alter_column('dialogue_turns', 'text',
               existing_type=sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('dialogue_turns', 'speaker_name',
               existing_type=sa.NVARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('dialogue_turns', 'speaker_label',
               existing_type=sa.NVARCHAR(length=40, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    # ### end Alembic commands ###
